// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Gets the [FirebaseOptions] for the current platform.
  /// Throws an [UnsupportedError] if the platform is not supported.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase configuration for Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA61GYPY8_eZkj3Tm01D_MFYAwsFqwnWrU',
    appId: '1:252578618828:android:58995d5f2ad864bb53d169',
    messagingSenderId: '252578618828',
    projectId: 'studyflow-ngnphcng',
    storageBucket: 'studyflow-ngnphcng.firebasestorage.app',
  );

  /// Firebase configuration for Web.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUK9cOXfWF4__1jGhgmyuc3TkduZy_tTU',
    appId: '1:252578618828:web:fc4153117be6df8b53d169',
    messagingSenderId: '252578618828',
    projectId: 'studyflow-ngnphcng',
    authDomain: 'studyflow-ngnphcng.firebaseapp.com',
    storageBucket: 'studyflow-ngnphcng.firebasestorage.app',
    measurementId: 'G-PHXWHPKD1B',
  );

  /// Firebase configuration for macOS.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXvIHtbGvgdoXKqw5L6A8k74TbR3b7IqI',
    appId: '1:252578618828:ios:e86c1b3415cfe36b53d169',
    messagingSenderId: '252578618828',
    projectId: 'studyflow-ngnphcng',
    storageBucket: 'studyflow-ngnphcng.firebasestorage.app',
    iosClientId: '252578618828-3g7j6pk4u8s5tedqkghapu0r97gl644o.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyflow',
  );

  /// Firebase configuration for iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXvIHtbGvgdoXKqw5L6A8k74TbR3b7IqI',
    appId: '1:252578618828:ios:e86c1b3415cfe36b53d169',
    messagingSenderId: '252578618828',
    projectId: 'studyflow-ngnphcng',
    storageBucket: 'studyflow-ngnphcng.firebasestorage.app',
    iosClientId: '252578618828-3g7j6pk4u8s5tedqkghapu0r97gl644o.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyflow',
  );

  /// Firebase configuration for Windows.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUK9cOXfWF4__1jGhgmyuc3TkduZy_tTU',
    appId: '1:252578618828:web:794bbfddfd466f1153d169',
    messagingSenderId: '252578618828',
    projectId: 'studyflow-ngnphcng',
    authDomain: 'studyflow-ngnphcng.firebaseapp.com',
    storageBucket: 'studyflow-ngnphcng.firebasestorage.app',
    measurementId: 'G-R04SZSZHZH',
  );

}