import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:studyflow/core/theme/app_colors.dart';
import 'package:studyflow/core/widgets/glass_card.dart';
import 'package:studyflow/features/focus/data/repositories/focus_repository.dart';
import 'package:studyflow/features/focus/data/models/focus_session_model.dart';
import 'package:studyflow/features/focus/presentation/screens/focus_heatmap_screen.dart';

class FocusScreen extends StatefulWidget {
  const FocusScreen({super.key});

  @override
  State<FocusScreen> createState() => _FocusScreenState();
}

class _FocusScreenState extends State<FocusScreen> with SingleTickerProviderStateMixin {
  late TabController _tabController;
  final FocusRepository _repository = FocusRepository();
  
  // Custom Timer State
  int _customMinutes = 30;
  
  // Pomodoro State (Default 25-5)
  final int _pomodoroWorkMinutes = 25;
  final int _pomodoroRestMinutes = 5;

  bool _isRunning = false;
  bool _isResting = false;
  int _secondsRemaining = 0;
  Timer? _timer;
  
  DateTime? _startTime;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
    _tabController.addListener(_onTabChanged);
    _secondsRemaining = _customMinutes * 60;
  }

  /// Triggers when the user switches between "Custom" and "Pomodoro" timer tabs.
  /// Sets initial remaining seconds depending on the selected tab.
  void _onTabChanged() {
    if (_isRunning) return; // Prevent changing tab while running
    setState(() {
      _isResting = false;
      if (_tabController.index == 0) {
        _secondsRemaining = _customMinutes * 60;
      } else {
        _secondsRemaining = _pomodoroWorkMinutes * 60;
      }
    });
  }

  /// Toggles the timer state between running and stopped.
  void _toggleTimer() {
    if (_isRunning) {
      _stopTimer();
    } else {
      _startTimer();
    }
  }

  /// Starts the focus session timer. 
  /// Spawns a periodic 1-second interval Timer that decrements remaining seconds.
  void _startTimer() {
    setState(() {
      _isRunning = true;
      _startTime = DateTime.now();
    });

    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      setState(() {
        if (_secondsRemaining > 0) {
          _secondsRemaining--;
        } else {
          _timer?.cancel();
          _onTimerComplete();
        }
      });
    });
  }

  /// Stops the active timer and cancels the periodic tick task.
  void _stopTimer() {
    _timer?.cancel();
    setState(() {
      _isRunning = false;
    });
    // In a real app, you might want to log this interrupted session to the backend here
  }

  /// Triggers when the timer successfully runs down to zero.
  /// If it was a work/focus session (not rest), it saves the completed focus session metadata to the backend.
  /// For Pomodoro tab, it switches state between Focus and Rest; for Custom tab, it resets to original custom duration.
  void _onTimerComplete() async {
    setState(() {
      _isRunning = false;
    });
    
    if (!_isResting && _startTime != null) {
      final duration = _tabController.index == 0 ? _customMinutes : _pomodoroWorkMinutes;
      final mode = _tabController.index == 0 ? "Custom" : "Pomodoro";
      
      final session = FocusSessionModel(
        id: '', // Generated by backend
        userId: '', // Set by backend based on token
        startTime: _startTime!,
        endTime: DateTime.now(),
        durationMinutes: duration,
        mode: mode,
        createdAt: DateTime.now(),
      );
      
      await _repository.saveFocusSession(session);
    }

    if (_tabController.index == 1) { // Pomodoro Mode
      setState(() {
        if (_isResting) {
          _isResting = false;
          _secondsRemaining = _pomodoroWorkMinutes * 60;
        } else {
          _isResting = true;
          _secondsRemaining = _pomodoroRestMinutes * 60;
        }
      });
    } else { // Custom Mode
      _secondsRemaining = _customMinutes * 60;
    }
  }

  /// Format seconds remaining to standard MM:SS string representation.
  String get _formattedTime {
    int minutes = _secondsRemaining ~/ 60;
    int seconds = _secondsRemaining % 60;
    return '${minutes.toString().padLeft(2, '0')}:${seconds.toString().padLeft(2, '0')}';
  }

  double get _progress {
    int totalSeconds;
    if (_tabController.index == 0) {
      totalSeconds = _customMinutes * 60;
    } else {
      totalSeconds = _isResting ? _pomodoroRestMinutes * 60 : _pomodoroWorkMinutes * 60;
    }
    return 1.0 - (_secondsRemaining / totalSeconds);
  }

  @override
  void dispose() {
    _timer?.cancel();
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    
    return Scaffold(
      backgroundColor: Colors.transparent,
      body: SafeArea(
          child: Column(
            children: [
              // Header
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const SizedBox(width: 48), // Balance for centering
                    Text(
                      'Focus Mode',
                      style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: theme.colorScheme.onSurface),
                    ),
                    IconButton(
                      icon: Icon(Icons.bar_chart_rounded, color: theme.colorScheme.onSurface),
                      tooltip: 'Focus Analytics',
                      onPressed: () {
                        Navigator.of(context).push(
                          MaterialPageRoute(
                            builder: (context) => const FocusHeatmapScreen(),
                          ),
                        );
                      },
                    ),
                  ],
                ),
              ),
              
              const SizedBox(height: 20),
              
              // Tabs
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 32.0),
                child: GlassCard(
                  padding: const EdgeInsets.all(4),
                  borderRadius: 30,
                  child: TabBar(
                    controller: _tabController,
                    indicator: BoxDecoration(
                      borderRadius: BorderRadius.circular(30),
                      color: AppColors.accent,
                    ),
                    splashBorderRadius: BorderRadius.circular(30),
                    labelColor: Colors.white,
                    unselectedLabelColor: theme.brightness == Brightness.dark
                        ? Colors.white.withValues(alpha: 0.7)
                        : Colors.black.withValues(alpha: 0.85),
                    labelStyle: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
                    unselectedLabelStyle: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
                    dividerColor: Colors.transparent,
                    tabs: const [
                      Tab(text: 'Custom'),
                      Tab(text: 'Pomodoro'),
                    ],
                  ),
                ),
              ),
              
              const Spacer(),
              
              // Timer Display
              Stack(
                alignment: Alignment.center,
                children: [
                  // Outer animated glow ring
                  if (_isRunning)
                    Container(
                      width: 280,
                      height: 280,
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        boxShadow: [
                          BoxShadow(
                            color: theme.colorScheme.primary.withValues(alpha: 0.3),
                            blurRadius: 40,
                            spreadRadius: 20,
                          ),
                        ],
                      ),
                    ).animate(onPlay: (controller) => controller.repeat())
                     .scale(begin: const Offset(0.9, 0.9), end: const Offset(1.1, 1.1), duration: 2.seconds)
                     .fade(begin: 0.5, end: 1.0, duration: 1.seconds)
                     .then()
                     .scale(begin: const Offset(1.1, 1.1), end: const Offset(0.9, 0.9), duration: 2.seconds)
                     .fade(begin: 1.0, end: 0.5, duration: 1.seconds),
                     
                  // Circular Progress Indicator
                  SizedBox(
                    width: 250,
                    height: 250,
                    child: CircularProgressIndicator(
                      value: _progress,
                      strokeWidth: 12,
                      backgroundColor: theme.colorScheme.onSurface.withValues(alpha: 0.15),
                      color: _isResting ? Colors.blueAccent : AppColors.accent,
                      strokeCap: StrokeCap.round,
                    ),
                  ),
                  
                  // Time Text
                  Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(
                        _formattedTime,
                        style: TextStyle(
                          fontSize: 64,
                          fontWeight: FontWeight.bold,
                          color: theme.colorScheme.onSurface,
                        ),
                      ),
                      if (_tabController.index == 1)
                        Text(
                          _isResting ? "REST" : "FOCUS",
                          style: TextStyle(
                            fontSize: 16,
                            letterSpacing: 2,
                            color: _isResting ? Colors.blueAccent : theme.colorScheme.primary,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                    ],
                  ),
                ],
              ),
              
              const Spacer(),
              
              // Controls
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  if (!_isRunning && _tabController.index == 0) // Only show Custom adjustment when not running
                    IconButton(
                      icon: Icon(Icons.remove_circle_outline, color: theme.colorScheme.onSurface, size: 32),
                      onPressed: () {
                        if (_customMinutes > 5) {
                          setState(() {
                            _customMinutes -= 5;
                            _secondsRemaining = _customMinutes * 60;
                          });
                        }
                      },
                    ),
                  const SizedBox(width: 20),
                  GestureDetector(
                    onTap: _toggleTimer,
                    child: GlassCard(
                      borderRadius: 40,
                      padding: const EdgeInsets.all(20),
                      color: _isRunning ? Colors.red.shade600 : AppColors.accent,
                      opacity: 0.95, // High opacity to prevent it from looking washed out
                      child: Icon(
                        _isRunning ? Icons.stop_rounded : Icons.play_arrow_rounded,
                        color: Colors.white,
                        size: 40,
                      ),
                    ),
                  ),
                  const SizedBox(width: 20),
                  if (!_isRunning && _tabController.index == 0) // Only show Custom adjustment when not running
                    IconButton(
                      icon: Icon(Icons.add_circle_outline, color: theme.colorScheme.onSurface, size: 32),
                      onPressed: () {
                        if (_customMinutes < 120) {
                          setState(() {
                            _customMinutes += 5;
                            _secondsRemaining = _customMinutes * 60;
                          });
                        }
                      },
                    ),
                ],
              ),
              
              const SizedBox(height: 100),
            ],
          ),
        ),
    );
  }
}
