import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:studyflow/core/services/notification/app_notification.dart';
import 'package:studyflow/core/services/notification/notification_service.dart';
import 'package:studyflow/core/services/notification/notification_type.dart';
import 'package:studyflow/core/utils/safe_change_notifier.dart';
import 'package:studyflow/features/auth/domain/entities/user_entity.dart';
import 'package:studyflow/features/auth/domain/usecase/check_auth_usecase.dart';
import 'package:studyflow/features/auth/domain/usecase/login_usecase.dart';
import 'package:studyflow/features/auth/domain/usecase/logout_usecase.dart';
import 'package:studyflow/features/auth/domain/usecase/register_usecase.dart';

class AuthViewmodel extends ChangeNotifier with SafeChangeNotifier {
  final RegisterUsecase registerUsecase;
  final LoginUsecase loginUsecase;
  final CheckAuthUsecase checkAuthUsecase;
  final LogoutUsecase logoutUsecase;
  StreamSubscription? _authSubscription;

  AuthViewmodel({
    required this.registerUsecase, 
    required this.loginUsecase,
    required this.checkAuthUsecase,
    required this.logoutUsecase,
  }) {
    _authSubscription = checkAuthUsecase().listen((user) {
      if (user != null) {
        isAuthenticated = true;
        currentUser = user;
      } else {
        isAuthenticated = false;
        currentUser = null;
      }
      isChecking = false;
      notifyListenersSafely();
    });
  }

  @override
  void dispose() {
    _authSubscription?.cancel();
    super.dispose();
  }

  bool isLoading = false;
  bool isChecking = true;
  bool isAuthenticated = false;
  UserEntity? currentUser;

  Future<String?> Register(String fullName, String username, String email, String password) async {
    try {
      isLoading = true;
      notifyListenersSafely();

      await registerUsecase(UserEntity(
        id: '', // Will be generated by Firebase
        fullName: fullName,
        username: username, 
        email: email,
      ), password);

      NotificationService.instance.show(
        AppNotification(message: "Register Successfully!", type: NotificationType.success)
      );

      return null;
    } catch (e) {
      NotificationService.instance.show(
        AppNotification(message: "Register failed!", type: NotificationType.error)
      );
      return e.toString().replaceFirst("Exception: ", "");
    } finally {
      isLoading = false;
      notifyListenersSafely();
    }
  }

  Future<String?> Login(String email, String password) async {
    try {
      isLoading = true;
      notifyListenersSafely();

      final user = await loginUsecase(
        email,
        password,
      );

      if (user == null) {
        NotificationService.instance.show(
          AppNotification(message: "Invalid credentials", type: NotificationType.error)
        );
        return "Invalid credentials";
      }
      
      NotificationService.instance.show(
        AppNotification(message: "Login Successfully", type: NotificationType.success)
      );
      return null;
    } catch (e) {
      NotificationService.instance.show(
        AppNotification(message: "Login failed", type: NotificationType.error)
      );
      return e.toString().replaceFirst("Exception: ", "");
    } finally {
      isLoading = false;
      notifyListenersSafely();
    }
  }

  Future<void> Logout() async {
    await logoutUsecase();
    NotificationService.instance.show(
      AppNotification(message: 'Logout success', type: NotificationType.success)
    );
  }
}